import { writeFile } from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SESSIONS_DIR = path.resolve(__dirname, '..', 'triage-sessions');

/**
 * Generate a bash script of mv commands for decided cards.
 *
 * @param {object} session  - Full session object
 * @param {boolean} includeSkipped - If true, include skipped cards (they
 *   cannot have destinations, so they are listed as comments)
 * @returns {Promise<{ scriptPath: string, script: string }>}
 */
export async function generateExportScript(session, includeSkipped = false) {
  const date = new Date().toISOString().slice(0, 10);
  const label = session.label || session.id;

  const optionMap = new Map(
    (session.options || []).map(o => [o.id, o])
  );

  // Group decided cards by option
  const byOption = new Map();
  const skippedCards = [];

  for (const card of session.cards) {
    if (card.decision === null) continue;
    if (card.decision === 'skip') {
      skippedCards.push(card);
      continue;
    }
    const opt = optionMap.get(card.decision);
    if (!opt) continue;
    if (!byOption.has(card.decision)) byOption.set(card.decision, []);
    byOption.get(card.decision).push(card);
  }

  const lines = [
    '#!/bin/bash',
    `# Media Triage Export — ${label} — ${date}`,
    '# Generated by Media Triage Tool',
    '# Review carefully before running. This script will move files.',
    '#',
    `# Session: ${session.id}`,
    `# Source:  ${session.sourceDir}`,
    '',
  ];

  for (const [optId, cards] of byOption) {
    const opt = optionMap.get(optId);
    if (!opt.destPath) {
      lines.push(`# --- ${opt.label} — leave in place (${cards.length} files) ---`);
      for (const card of cards) {
        lines.push(`# (keep) ${card.fullPath}`);
      }
      lines.push('');
      continue;
    }

    lines.push(`# --- ${opt.label} (${cards.length} files) ---`);
    for (const card of cards) {
      const dest = path.posix.join(opt.destPath, card.filename);
      lines.push(`mv ${quoteShell(card.fullPath)} ${quoteShell(dest)}`);
    }
    lines.push('');
  }

  if (includeSkipped && skippedCards.length > 0) {
    lines.push(`# --- Skipped (${skippedCards.length} files — no action) ---`);
    for (const card of skippedCards) {
      lines.push(`# ${card.fullPath}`);
    }
    lines.push('');
  }

  const script = lines.join('\n');

  // Save with a timestamp suffix to avoid overwriting previous exports
  const safeName = session.id;
  const timestamp = Date.now();
  const scriptFilename = `${safeName}-export-${timestamp}.sh`;
  const scriptPath = path.join(SESSIONS_DIR, scriptFilename);

  await writeFile(scriptPath, script, { encoding: 'utf8', mode: 0o755 });

  return { scriptPath, script };
}

function quoteShell(str) {
  // Wrap in double quotes, escaping any double quotes in the path
  return `"${str.replace(/"/g, '\\"')}"`;
}
